server {
  listen 8080;
  server_name _;
  root /usr/share/nginx/html;
  index index.html;

  location = /runtime-config.js {
    add_header Cache-Control "no-store";
    add_header Content-Type "application/javascript";
    try_files $uri =404;
  }

  location / {
    try_files $uri $uri/ /index.html;
  }
}
